export default {
    // AUTH ACTIONS
    // Center actions
    LOAD_CENTERS: 'LOAD_CENTERS',
    CREATE_CENTER: 'CREATE_CENTER',
    UPDATE_CENTER: 'UPDATE_CENTER',
    DELETE_CENTER: 'DELETE_CENTER',

    // User actions
    ADD_TO_CART: 'ADD_TO_CART',
    REGISTER_USER: 'REGISTER_USER',
    UPDATE_USER: 'UPDATE_USER',
    LOAD_USER: 'LOAD_USER',

    //    LOGOUT: 'LOGOUT',

    // ACTIVITIES ACTIONS
    LOAD_ACTIVITIES: 'LOAD_ACTIVITIES',
    LOAD_ACTIVITY: 'LOAD_ACTIVITY',
    CREATE_ACTIVITY: 'CREATE_ACTIVITY',
    DELETE_ACTIVITY: 'DELETE_ACTIVITY',
    UPDATE_ACTIVITY: 'UPDATE_ACTIVITY',

    // SPORTS ACTIONS
    LOAD_SPORTS: 'LOAD_SPORTS'
};
